USE [master]
GO
/****** Object:  Database [BD_JAPAMA]    Script Date: 25/04/2025 03:22:58 p. m. ******/
CREATE DATABASE [BD_JAPAMA]
    CONTAINMENT = NONE
    ON  PRIMARY
    ( NAME = N'BD_JAPAMA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BD_JAPAMA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
    LOG ON
    ( NAME = N'BD_JAPAMA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BD_JAPAMA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BD_JAPAMA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
    begin
        EXEC [BD_JAPAMA].[dbo].[sp_fulltext_database] @action = 'enable'
    end
GO
ALTER DATABASE [BD_JAPAMA] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [BD_JAPAMA] SET ANSI_NULLS OFF
GO
ALTER DATABASE [BD_JAPAMA] SET ANSI_PADDING OFF
GO
ALTER DATABASE [BD_JAPAMA] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [BD_JAPAMA] SET ARITHABORT OFF
GO
ALTER DATABASE [BD_JAPAMA] SET AUTO_CLOSE ON
GO
ALTER DATABASE [BD_JAPAMA] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [BD_JAPAMA] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [BD_JAPAMA] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [BD_JAPAMA] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [BD_JAPAMA] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [BD_JAPAMA] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [BD_JAPAMA] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [BD_JAPAMA] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [BD_JAPAMA] SET  ENABLE_BROKER
GO
ALTER DATABASE [BD_JAPAMA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [BD_JAPAMA] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [BD_JAPAMA] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [BD_JAPAMA] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [BD_JAPAMA] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [BD_JAPAMA] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [BD_JAPAMA] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [BD_JAPAMA] SET RECOVERY SIMPLE
GO
ALTER DATABASE [BD_JAPAMA] SET  MULTI_USER
GO
ALTER DATABASE [BD_JAPAMA] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [BD_JAPAMA] SET DB_CHAINING OFF
GO
ALTER DATABASE [BD_JAPAMA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [BD_JAPAMA] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [BD_JAPAMA] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [BD_JAPAMA] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
ALTER DATABASE [BD_JAPAMA] SET QUERY_STORE = ON
GO
ALTER DATABASE [BD_JAPAMA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BD_JAPAMA]
GO
/****** Object:  Schema [Clientes]    Script Date: 25/04/2025 03:22:58 p. m. ******/
CREATE SCHEMA [Clientes]
GO
/****** Object:  Schema [Inventarios]    Script Date: 25/04/2025 03:22:58 p. m. ******/
CREATE SCHEMA [Inventarios]
GO
/****** Object:  Schema [Personas]    Script Date: 25/04/2025 03:22:58 p. m. ******/
CREATE SCHEMA [Personas]
GO
/****** Object:  Schema [RecursosHumanos]    Script Date: 25/04/2025 03:22:58 p. m. ******/
CREATE SCHEMA [RecursosHumanos]
GO
/****** Object:  Schema [Servicios]    Script Date: 25/04/2025 03:22:58 p. m. ******/
CREATE SCHEMA [Servicios]
GO
/****** Object:  Schema [Sucursales]    Script Date: 25/04/2025 03:22:58 p. m. ******/
CREATE SCHEMA [Sucursales]
GO
USE [master]
GO
ALTER DATABASE [BD_JAPAMA] SET  READ_WRITE
GO
